/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadoravdd;

import javax.swing.JOptionPane;

/**
 *
 * @author IFMS
 */
public class calculadora extends javax.swing.JFrame {

    /**
     * Creates new form calculadora
     */
    public calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sete = new javax.swing.JButton();
        oito = new javax.swing.JButton();
        nove = new javax.swing.JButton();
        cinco = new javax.swing.JButton();
        seis = new javax.swing.JButton();
        quatro = new javax.swing.JButton();
        tres = new javax.swing.JButton();
        dois = new javax.swing.JButton();
        um = new javax.swing.JButton();
        mais = new javax.swing.JButton();
        menos = new javax.swing.JButton();
        divisor = new javax.swing.JButton();
        vezes = new javax.swing.JButton();
        apagar = new javax.swing.JButton();
        resultado = new javax.swing.JLabel();
        resultado1 = new javax.swing.JTextField();
        zero = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sete.setText("7");
        sete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seteActionPerformed(evt);
            }
        });

        oito.setText("8");
        oito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oitoActionPerformed(evt);
            }
        });

        nove.setText("9");
        nove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noveActionPerformed(evt);
            }
        });

        cinco.setText("5");
        cinco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoActionPerformed(evt);
            }
        });

        seis.setText("6");
        seis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisActionPerformed(evt);
            }
        });

        quatro.setText("4");
        quatro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quatroActionPerformed(evt);
            }
        });

        tres.setText("3");
        tres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresActionPerformed(evt);
            }
        });

        dois.setText("2");
        dois.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doisActionPerformed(evt);
            }
        });

        um.setText("1");
        um.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                umActionPerformed(evt);
            }
        });

        mais.setText("+");
        mais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maisActionPerformed(evt);
            }
        });

        menos.setText("-");
        menos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menosActionPerformed(evt);
            }
        });

        divisor.setText("/");
        divisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisorActionPerformed(evt);
            }
        });

        vezes.setText("*");
        vezes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vezesActionPerformed(evt);
            }
        });

        apagar.setText("Apagar");
        apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apagarActionPerformed(evt);
            }
        });

        resultado.setText("resultado ");

        resultado1.setEditable(false);

        zero.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(quatro)
                    .addComponent(sete)
                    .addComponent(tres))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(resultado1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(oito)
                            .addComponent(cinco)
                            .addComponent(dois))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nove)
                            .addComponent(seis)
                            .addComponent(um))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(menos)
                            .addComponent(mais)
                            .addComponent(zero))
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(vezes)
                            .addComponent(divisor)
                            .addComponent(apagar, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(sete)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(oito)
                        .addComponent(nove)
                        .addComponent(mais)
                        .addComponent(divisor)))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cinco)
                    .addComponent(seis)
                    .addComponent(quatro)
                    .addComponent(menos)
                    .addComponent(vezes))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dois)
                    .addComponent(tres)
                    .addComponent(um)
                    .addComponent(apagar)
                    .addComponent(zero))
                .addGap(18, 18, 18)
                .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(resultado1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void seteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seteActionPerformed
        //JOptionPane.showMessageDialog(cinco, sete.getActionCommand());
        resultado1.setText(sete.getActionCommand());
        if(operacao=='+'||operacao=='+'||operacao=='/'||operacao=='*'){      
        operando2=Integer.parseInt(sete.getActionCommand());
        if(operacao=='+'){
            resul=operando1+operando2;
            resultado1.setText(String.valueOf(resul));
            
        }
        if(operacao=='-'){
            resul=operando1-operando2;
            resultado1.setText(String.valueOf(resul));
            
        }
        if(operacao=='/'){
            resul=operando1/operando2;
            resultado1.setText(String.valueOf(resul));
            
        }
        if(operacao=='*'){
            resul=operando1*operando2;
            resultado1.setText(String.valueOf(resul));
            
        }
        }
        
        else{ 
            operando1=Integer.parseInt(sete.getActionCommand());
            
        } 
    }//GEN-LAST:event_seteActionPerformed

    private void maisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maisActionPerformed
        operacao=mais.getActionCommand().charAt(0);
    }//GEN-LAST:event_maisActionPerformed

    private void oitoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oitoActionPerformed
        // TODO add your handling code here:
        resultado1.setText(oito.getActionCommand());
        if(operacao=='+'||operacao=='+'||operacao=='/'||operacao=='*'){      
        operando2=Integer.parseInt(oito.getActionCommand());
        if(operacao=='+'){
            resul=operando1+operando2;
            resultado1.setText(String.valueOf(resul));
            
        }
        if(operacao=='-'){
            resul=operando1-operando2;
            resultado1.setText(String.valueOf(resul));
            
        }
        if(operacao=='/'){
            resul=operando1/operando2;
            resultado1.setText(String.valueOf(resul));
            
        }
        if(operacao=='*'){
            resul=operando1*operando2;
            resultado1.setText(String.valueOf(resul));
            
        }
        }
        
        else{ 
            operando1=Integer.parseInt(oito.getActionCommand());
            
        } 
    }//GEN-LAST:event_oitoActionPerformed

    private void menosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menosActionPerformed
operacao=menos.getActionCommand().charAt(0);        
    }//GEN-LAST:event_menosActionPerformed

    private void divisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisorActionPerformed
       operacao=divisor.getActionCommand().charAt(0);
    }//GEN-LAST:event_divisorActionPerformed

    private void vezesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vezesActionPerformed
        operacao=vezes.getActionCommand().charAt(0);
    }//GEN-LAST:event_vezesActionPerformed

    private void noveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noveActionPerformed
        // TODO add your handling code here:
        resultado1.setText(nove.getActionCommand());
        if(operacao=='+'||operacao=='+'||operacao=='/'||operacao=='*'){      
        operando2=Integer.parseInt(nove.getActionCommand());
        if(operacao=='+'){
            resul=operando1+operando2;
            resultado1.setText(String.valueOf(resul));
            
        }
        if(operacao=='-'){
            resul=operando1-operando2;
            resultado1.setText(String.valueOf(resul));
            
        }
        if(operacao=='/'){
            resul=operando1/operando2;
            resultado1.setText(String.valueOf(resul));
            
        }
        if(operacao=='*'){
            resul=operando1*operando2;
            resultado1.setText(String.valueOf(resul));
            
        }
        }
        
        else{ 
            operando1=Integer.parseInt(nove.getActionCommand());
            
        } 
    }//GEN-LAST:event_noveActionPerformed

    private void quatroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quatroActionPerformed
        // TODO add your handling code here:
        
       resultado1.setText(quatro.getActionCommand());
        if(operacao=='+'||operacao=='+'||operacao=='/'||operacao=='*'){      
        operando2=Integer.parseInt(quatro.getActionCommand());
        if(operacao=='+'){
            resul=operando1+operando2;
            resultado1.setText(String.valueOf(resul));
            
        }
        if(operacao=='-'){
            resul=operando1-operando2;
            resultado1.setText(String.valueOf(resul));
            
        }
        if(operacao=='/'){
            resul=operando1/operando2;
            resultado1.setText(String.valueOf(resul));
            
        }
        if(operacao=='*'){
            resul=operando1*operando2;
            resultado1.setText(String.valueOf(resul));
            
        }
        }
        
        else{ 
            operando1=Integer.parseInt(quatro.getActionCommand());
            
        } 
    }//GEN-LAST:event_quatroActionPerformed

    private void cincoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoActionPerformed
        // TODO add your handling code here:
        resultado1.setText(cinco.getActionCommand());
        if(operacao=='+'||operacao=='+'||operacao=='/'||operacao=='*'){      
        operando2=Integer.parseInt(cinco.getActionCommand());
        if(operacao=='+'){
            resul=operando1+operando2;
            resultado1.setText(String.valueOf(resul));
            
        }
        if(operacao=='-'){
            resul=operando1-operando2;
            resultado1.setText(String.valueOf(resul));
            
        }
        if(operacao=='/'){
            resul=operando1/operando2;
            resultado1.setText(String.valueOf(resul));
            
        }
        if(operacao=='*'){
            resul=operando1*operando2;
            resultado1.setText(String.valueOf(resul));
            
        }
        }
        
        else{ 
            operando1=Integer.parseInt(cinco.getActionCommand());
            
        } 
    }//GEN-LAST:event_cincoActionPerformed

    private void seisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisActionPerformed
        // TODO add your handling code here:
        resultado1.setText(seis.getActionCommand());
        if(operacao=='+'||operacao=='+'||operacao=='/'||operacao=='*'){      
        operando2=Integer.parseInt(seis.getActionCommand());
        if(operacao=='+'){
            resul=operando1+operando2;
            resultado1.setText(String.valueOf(resul));
            
        }
        if(operacao=='-'){
            resul=operando1-operando2;
            resultado1.setText(String.valueOf(resul));
            
        }
        if(operacao=='/'){
            resul=operando1/operando2;
            resultado1.setText(String.valueOf(resul));
            
        }
        if(operacao=='*'){
            resul=operando1*operando2;
            resultado1.setText(String.valueOf(resul));
            
        }
        }
        
        else{ 
            operando1=Integer.parseInt(seis.getActionCommand());
            
        } 
    }//GEN-LAST:event_seisActionPerformed

    private void tresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresActionPerformed
        // TODO add your handling code here:
        resultado1.setText(tres.getActionCommand());
        if(operacao=='+'||operacao=='+'||operacao=='/'||operacao=='*'){      
        operando2=Integer.parseInt(tres.getActionCommand());
        if(operacao=='+'){
            resul=operando1+operando2;
            resultado1.setText(String.valueOf(resul));
            
        }
        if(operacao=='-'){
            resul=operando1-operando2;
            resultado1.setText(String.valueOf(resul));
            
        }
        if(operacao=='/'){
            resul=operando1/operando2;
            resultado1.setText(String.valueOf(resul));
            
        }
        if(operacao=='*'){
            resul=operando1*operando2;
            resultado1.setText(String.valueOf(resul));
            
        }
        }
        
        else{ 
            operando1=Integer.parseInt(tres.getActionCommand());
            
        } 
    }//GEN-LAST:event_tresActionPerformed

    private void doisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doisActionPerformed
        // TODO add your handling code here:
        resultado1.setText(dois.getActionCommand());
        if(operacao=='+'||operacao=='+'||operacao=='/'||operacao=='*'){      
        operando2=Integer.parseInt(dois.getActionCommand());
        if(operacao=='+'){
            resul=operando1+operando2;
            resultado1.setText(String.valueOf(resul));
            
        }
        if(operacao=='-'){
            resul=operando1-operando2;
            resultado1.setText(String.valueOf(resul));
            
        }
        if(operacao=='/'){
            resul=operando1/operando2;
            resultado1.setText(String.valueOf(resul));
            
        }
        if(operacao=='*'){
            resul=operando1*operando2;
            resultado1.setText(String.valueOf(resul));
            
        }
        }
        
        else{ 
            operando1=Integer.parseInt(dois.getActionCommand());
            
        } 
    }//GEN-LAST:event_doisActionPerformed

    private void umActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_umActionPerformed
        // TODO add your handling code here:
        resultado1.setText(um.getActionCommand());
        if(operacao=='+'||operacao=='+'||operacao=='/'||operacao=='*'){      
        operando2=Integer.parseInt(um.getActionCommand());
        if(operacao=='+'){
            resul=operando1+operando2;
            resultado1.setText(String.valueOf(resul));
            
        }
        if(operacao=='-'){
            resul=operando1-operando2;
            resultado1.setText(String.valueOf(resul));
            
        }
        if(operacao=='/'){
            resul=operando1/operando2;
            resultado1.setText(String.valueOf(resul));
            
        }
        if(operacao=='*'){
            resul=operando1*operando2;
            resultado1.setText(String.valueOf(resul));
            
        }
        }
        
        else{ 
            operando1=Integer.parseInt(um.getActionCommand());
            
        } 
    }//GEN-LAST:event_umActionPerformed

    private void apagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apagarActionPerformed
        // TODO add your handling code here:
        operacao=',';
        resultado1.setText(String.valueOf("0"));
    }//GEN-LAST:event_apagarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadora().setVisible(true);
            }
        });
    }

    private int operando1;
    private int operando2;
    private char operacao;
    private int resul;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton apagar;
    private javax.swing.JButton cinco;
    private javax.swing.JButton divisor;
    private javax.swing.JButton dois;
    private javax.swing.JButton mais;
    private javax.swing.JButton menos;
    private javax.swing.JButton nove;
    private javax.swing.JButton oito;
    private javax.swing.JButton quatro;
    private javax.swing.JLabel resultado;
    private javax.swing.JTextField resultado1;
    private javax.swing.JButton seis;
    private javax.swing.JButton sete;
    private javax.swing.JButton tres;
    private javax.swing.JButton um;
    private javax.swing.JButton vezes;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
